version: 1.0.{build}
build_script:
- pwsh: >-
    Install-Module -Name Pester -Force;
    Import-Module Pester;
    Invoke-Pester -OutputFile TestResults.xml -OutputFormat NUnitXml;
    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/${env:APPVEYOR_JOB_ID}", (Join-Path $PWD 'TestResults.xml'))